# Generated by Django 5.0.7 on 2024-07-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Task',
        ),
    ]
